version: "3.7"

services:
  chrome:
    image: selenium/standalone-chrome:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm  # to use the host's shared memory ref. https://github.com/SeleniumHQ/docker-selenium#running-the-images
    ports:
      - 4444:4444
    restart: unless-stopped
